kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-upstream-providers-{{ include "minio-proxy.fullname" . }}
data: 
  minio.conf: |
    upstream minio {
      server {{ .Values.minio.host }}:{{ .Values.minio.port | default "9000" }};
    }
