kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config-{{ include "minio-proxy.fullname" . }}
data:
  default.conf: |
    include upstream_providers.d/*.conf;
    include sites-enabled/*.conf;
